apiVersion: v1
kind: Service
metadata:
  name: todo-service-abayk
  labels:
    app: todo-abayk
    author: abayk
spec:
  type: NodePort
  selector:
    app: todo-abayk
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
